- name: Stop transmission
  shell: "~/stop-transmission.sh"
  become: true
  become_user: "{{ username }}"

- name: Stop dir2rss
  shell: "~/dir2rss/stop.sh"
  become: true
  become_user: "{{ username }}"

- name: Find http_port
  shell: "jq '.http_port' ~/seedbox-settings.json"
  become: true
  become_user: "{{ username }}"
  register: http_port

- name: Find peer_port
  shell: "jq '.peer_port' ~/seedbox-settings.json"
  become: true
  become_user: "{{ username }}"
  register: peer_port

- name: Find a uuid of an external disk
  shell: "blkid | grep sdb1 | awk '{print $2}' | sed 's/\"//g'"
  register: uuid

- name: Remove /home/{{ username }} with external disk {{ uuid.stdout }}
  mount:
    path: "/home/{{ username }}"
    src: "{{ uuid.stdout }}"
    fstype: xfs
    state: absent
    opts: nofail
  when: uuid.stdout != ""

- name: Delete user {{ username }}
  user:
    name: "{{ username }}"
    state: absent
    shell: /bin/bash

- name: Remove /home/{{ username }} directory
  file:
    path: "/home/{{ username }}"
    state: absent

- name: Close {{ http_port.stdout }} port
  iptables:
    chain: INPUT
    protocol: "{{ item }}"
    destination_port: "{{ http_port.stdout }}"
    jump: ACCEPT
    state: absent
  with_items:
    - tcp
    - udp

- name: Close {{ peer_port.stdout }} port
  iptables:
    chain: INPUT
    protocol: "{{ item }}"
    destination_port: "{{ peer_port.stdout }}"
    jump: ACCEPT
    state: absent
  with_items:
    - tcp
    - udp

- name: Uninstall packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - transmission-daemon
    - transmission-common
