- name: install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - transmission-daemon
    - git
    - ruby
    - rubygem-sinatra
    - jq
    - moreutils

- name: Check {{ username }} directory
  stat:
    path: "/home/{{ username }}"
  register: downloads

- name: Create {{ username }}  directory
  file:
    path: "/home/{{ username }}"
    state: directory
    mode: 0775
  when: downloads.stat.exists == false

- name: Find a uuid of an external disk
  shell: "blkid | grep sdb1 | awk '{print $2}' | sed 's/\"//g'"
  register: uuid

- name: Mount /home/{{ username }} with external disk {{ uuid.stdout }}
  mount:
    path: "/home/{{ username }}"
    src: "{{ uuid.stdout }}"
    fstype: xfs
    state: mounted
    opts: nofail
  when: uuid.stdout != ""

- name: Add user {{ username }}
  user:
    name: "{{ username }}"
    group: nginx
    shell: /bin/bash

- name: Opening rx to group nginx for home directory
  file:
    path: "/home/{{ username }}"
    mode: 0750

- name: Copy seedbox-settings.json
  template:
    src: seedbox-settings.json.j2
    dest: ~/seedbox-settings.json
    mode: 0700
  become: true
  become_user: "{{ username }}"

- name: Copy start-transmission.sh
  template:
    src: start-transmission.sh.j2
    dest: ~/start-transmission.sh
    mode: 0700
  become: true
  become_user: "{{ username }}"
  
- name: Copy update-blocklist.sh
  template:
    src: update-blocklist.sh.j2
    dest: ~/update-blocklist.sh
    mode: 0700
  become: true
  become_user: "{{ username }}"

#- name: Copy rss.xslt
#  template:
#    src: rss.xslt.j2
#    dest: ~/rss.xslt
#    mode: 0700
#  become: true
#  become_user: "{{ username }}"

- name: Open {{ http_port }} port
  iptables:
    action: insert
    chain: INPUT
    protocol: "{{ item }}"
    destination_port: "{{ http_port }}"
    jump: ACCEPT
    rule_num: 2
  with_items:
    - tcp
    - udp

- name: Open {{ peer_port }} port
  iptables:
    action: insert
    chain: INPUT
    protocol: "{{ item }}"
    destination_port: "{{ peer_port }}"
    jump: ACCEPT
    rule_num: 2 
  with_items:
    - tcp
    - udp

- name: Create transmission-{{ username }}.service
  template:
    src: transmission.service.j2
    dest: /etc/systemd/system/transmission-{{ username }}.service
    owner: root
    group: root
    mode: 0644

- name: Restart service transmission-{{ username }}
  service:
    name: "transmission-{{ username }}"
    state: restarted
    enabled: yes

- name: Create nginx {{ username }}.conf
  template:
    src: nginxinc.conf.j2
    dest: /etc/nginx/default.d/{{ username }}.conf
    mode: 0644

- name: Restart service nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Download dir2rss from git
  git:
    repo: "https://github.com/ThaiDangFr/dir2rss.git"
    dest: "~/dir2rss"
    force: yes
  become: true
  become_user: "{{ username }}"

- name: Configure dir2rss
  shell: "jq '.directory = \"/home/{{ username }}/Downloads\"' web.json | sponge web.json"
  args:
    chdir: ~/dir2rss
  become: true
  become_user: "{{ username }}"

- name: Configure dir2rss
  shell: "jq '.baseurl = \"http://{{ inventory_hostname }}/{{ username }}\"' web.json | sponge web.json"
  args:
    chdir: ~/dir2rss
  become: true
  become_user: "{{ username }}"

- name: Create dir2rss-{{ username }}.service
  template:
    src: dir2rss.service.j2
    dest: /etc/systemd/system/dir2rss-{{ username }}.service
    owner: root
    group: root
    mode: 0644

- name: Restart service dir2rss-{{ username }}
  service:
    name: "dir2rss-{{ username }}"
    state: restarted
    enabled: yes
