- name: install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - transmission-daemon
    - nginx

- name: Check {{ username }} directory
  stat:
    path: "/home/{{ username }}"
  register: downloads

- name: Create {{ username }}  directory
  file:
    path: "/home/{{ username }}"
    state: directory
    mode: 0775
  when: downloads.stat.exists == false

- name: Find a uuid of an external disk
  shell: "blkid | grep sdb1 | awk '{print $2}' | sed 's/\"//g'"
  register: uuid

- name: Mount /home/{{ username }} with external disk {{ uuid.stdout }}
  mount:
    path: "/home/{{ username }}"
    src: "{{ uuid.stdout }}"
    fstype: xfs
    state: mounted
    opts: nofail
  when: uuid.stdout != ""


- name: Add user {{ username }}
  user:
    name: "{{ username }}"
    group: nginx
    shell: /bin/bash

- name: Opening rx to group nginx for home directory
  file:
    path: "/home/{{ username }}"
    mode: 0750

- name: Copy start-transmission.sh
  template:
    src: start-transmission.sh.j2
    dest: ~/start-transmission.sh
    mode: 0700
  become: true
  become_user: "{{ username }}"
  
- name: Copy stop-transmission.sh
  template:
    src: stop-transmission.sh.j2
    dest: ~/stop-transmission.sh
    mode: 0700
  become: true
  become_user: "{{ username }}"

- name: Copy rss.xslt
  template:
    src: rss.xslt.j2
    dest: ~/rss.xslt
    mode: 0700
  become: true
  become_user: "{{ username }}"

- name: Open {{ http_port }} port
  iptables:
    action: insert
    chain: INPUT
    protocol: "{{ item }}"
    destination_port: "{{ http_port }}"
    jump: ACCEPT
    rule_num: 2
  with_items:
    - tcp
    - udp

- name: Open {{ peer_port }} port
  iptables:
    action: insert
    chain: INPUT
    protocol: "{{ item }}"
    destination_port: "{{ peer_port }}"
    jump: ACCEPT
    rule_num: 2 
  with_items:
    - tcp
    - udp
 
- name: Stop transmission
  shell: "~/stop-transmission.sh"
  become: true
  become_user: "{{ username }}"


- name: Start transmission
  shell: "~/start-transmission.sh"
  become: true
  become_user: "{{ username }}"

- name: Open 80 port
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    rule_num: 2 

- name: Create nginx {{ username }}.conf
  template:
    src: nginxinc.conf.j2
    dest: /etc/nginx/conf.d/{{ username }}.conf
    mode: 0644


- name: Restart service nginx
  service:
    name: nginx
    state: restarted
    enabled: yes



  