- name: Add passenger repo
  get_url:
    url: https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo
    dest: /etc/yum.repos.d/passenger.repo
    mode: 0644    

- name: Install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - nginx
    - passenger

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Find passenger_root
  shell: "passenger-config --root"
  register: passenger_root

- name: Copy passenger.conf
  template:
    src: passenger.conf.j2
    dest: /etc/nginx/conf.d/passenger.conf
    owner: root
    group: root
    mode: 0644

- name: Start service nginx, if not started
  service:
    name: nginx
    state: started
    enabled: yes

- name: Check if firewalld package is not installed
  yum:
    list=firewalld
  register: yum_list

- name: Open 80 port
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    rule_num: 2  
  when: yum_list.results | selectattr("yumstate", "match", "installed") | list | length == 0

