- name: Add chrome repository
  yum_repository:
    name: google-chrome
    description: google chrome repo
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - nginx
    - passenger

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest


- name: Check if firewalld package is not installed
  yum:
    list=firewalld
  register: yum_list

- name: Open 80 port
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    rule_num: 2  
  when: yum_list.results | selectattr("yumstate", "match", "installed") | list | length == 0

